# 1. Backend 앱 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: junseok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # [중요] 아까 푸시한 이미지 주소입니다.
          image: junseok6523/gangwon-junseok-backend:lite
          ports:
            - containerPort: 8000
          # 위에서 만든 ConfigMap과 Secret을 가져와서 씁니다.
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

---
# 2. Backend 서비스 (외부 공개용 대문)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: junseok
spec:
  selector:
    app: backend
  type: LoadBalancer # 외부 접속 허용
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000